# Setup
title: Vyret
tagline: NÃ¥r Vy ikke strekker til
url: https://kyrremann.no/vyret
baseurl: "/vyret"

goat_counter: kyrremann

# Optimize Jekyll
exclude:
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
